---
abstract: 'fast Date framework in C.'
author:
  - unknown
build_requires:
  Test::Simple: 0.96
configure_requires:
  File::ShareDir::Install: 0.07
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Panda-Date
no_index:
  directory:
    - t
    - inc
requires:
  File::ShareDir: 0
  Panda::Export: 0
  Test::Deep: 0
version: v2.2.0
